version: '3.8'
services:
    db:
        image: mysql:5.7
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_USER: gestambu
            MYSQL_DATABASE: gestambu
            MYSQL_PASSWORD: gestambu
            MYSQL_ROOT_PASSWORD: gestambu 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html
        links:
            - db
        networks:
            - default
    adminer:
        image: adminer
        restart: unless-stopped
        ports:
        - 8080:8080
        networks:
            - default
volumes:
    persistent: